### ISSUE TITLE
Installation fails when executed in directory with no write permissions

### ISSUE THREAD

**Issue by roele** [cometkim/asdf-bun#10]
If `asdf install bun latest` is executed in a directory where the user has no write permissions (e.g. `/`) the installation will fail with following error. 

```shell
user@host /
  ❯ asdf install bun latest
mktemp: mkdtemp failed on asdf-bun.rWz6: Read-only file system
Downloading Bun v0.5.6...
curl: (23) Failure writing output to destination
Fail: Couldn't download the Bun binary from https://github.com/oven-sh/bun/releases/download/bun-v0.5.6/bun-darwin-aarch64.zip
Fail: Failed to download Bun v0.5.6
```

This is due to the fact the `mktemp` tried to crate a temporary directory in `/`. Maybe the command should enforce creating that directoy in `/temp`.

...
Environment: `macBook Pro M1, macOS 13.2, fish shell 3.6.0`

**Comment by cometkim** [comment]
I think you need to remount your file system to be rw

**Comment by roele** [comment]
I'm on macOS where since [Catalina](https://support.apple.com/en-us/HT210650) the root is not writeable anymore by default.

I think an easy fix would be to force creation in `/tmp` instead.

```
function get_temp_dir() {
  local tmpdir
  tmpdir=$(mktemp -d /tmp/asdf-bun.XXXX)

  echo -n "$tmpdir"
}
```

**Comment by cometkim** [comment]
That's exactly what it does

https://github.com/cometkim/asdf-bun/blob/main/lib/utils.bash#L65-L70

**Comment by cometkim** [comment]
Do you have a different `$TMPDIR` rather than `/tmp` ?

**Comment by roele** [comment]
That's actually not what it does on macOS. The command `mktemp -d asdf.XXXX` tries to create the directory where you execute the command. In case of `/` it tries to create it in root `/asdf.XXXX`. That seems to be the case even on Linux.

Also the $TMPDIR variable is only used if the `-t` option is set, according to the man page. Even though the man page mentions various fallback paths its examples all refer use a `/temp` prefix. So the proper fix would probably be to use the `-t` flag instead of `-d`.
