### ISSUE TITLE
bunx does not get created with bun 1.0

### ISSUE THREAD

**Issue by brw** [cometkim/asdf-bun#11]
The bash script you're using to compare semver versions doesn't seem to work properly with major version number differences (https://github.com/davidaurelio/shell-semver/issues/2). So with version 1.0.0 out the version check at https://github.com/cometkim/asdf-bun/blob/fd84eddba7ede5efde5b5a476ac936feb1fde81c/bin/install#L27 now fails.

Don't know how complicated you want to make it but https://github.com/Ariel-Rodriguez/sh-semversion-2 seems like a pretty solid alternative. Or maybe just check if `bun x` exists?

**Comment by cometkim** [comment]
Thanks for reporting this. `asdf plugin update bun` then it works.
