### ISSUE TITLE
getting illegal hardware instruction for any command

### ISSUE THREAD

**Issue by 3commascapital** [cometkim/asdf-bun#15]
`[1]    40214 illegal hardware instruction  bun -v`

i tried a few versions, but ended up eventually just shifting back to direct bun install for short term

**Comment by cometkim** [comment]
Hmm, has the issue been happening since recently?

Or, can you describe your environment?

**Comment by 3commascapital** [comment]
mac m1: 13.5.2 (22G91)
steps:
```
✗ bun -v
zsh: command not found: bun
✗ asdf install bun 1.0.1
Downloading Bun v1.0.1...
Archive:  /var/folders/j0/qxnj38ld075bj80p9hs2dqlw0000gn/T/asdf-bun.09Zc/bun.zip
  inflating: ~/.asdf/downloads/bun/1.0.1/bun  
Installing Bun v1.0.1...
Bun v1.0.1 is installed successfully!
✗ bun -v
[1]    80834 illegal hardware instruction  bun -v
```

**Comment by cometkim** [comment]
Please share the results of `uname -a`

**Comment by 3commascapital** [comment]
```
Darwin ... 22.6.0 Darwin Kernel Version 22.6.0: ...; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 x86_64 i386 Darwin
```

**Comment by cometkim** [comment]
It's confusing. You have an m1 arm machine, but `uname -m` prints `x86_64`? It doesn't seem usual.

**Comment by cometkim** [comment]
I guess you ran it on Rosetta or something

**Comment by 3commascapital** [comment]
ok, yeah, could be my setup. i had some flags, so when i used this alias
```bash
alias ibrew='arch -x86_64 /usr/local/bin/brew'
```
it seemed to work fine
```
✗ bun -v
1.0.2
```
