### ISSUE TITLE
listing all versions fails silently

### ISSUE THREAD

**Issue by nurrony** [cometkim/asdf-bun#16]
I have installed this plugin to manage `bun`. Right after installing this plugin, I executed the following command and please check the snap for details.
```sh
asdf list all bun
```
<img width="583" alt="snapshot-20231006111859@2x" src="https://github.com/cometkim/asdf-bun/assets/2513341/9db59620-affb-4222-9ae0-4bdd3da561ad">

Here are other relevant informations 

**Output of `asdf info`**
```
OS:
Darwin Nurs-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:23 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

BASH VERSION:
5.2.15(1)-release

ASDF VERSION:
v0.13.1-0586b37

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/Users/nurrony/.asdf
ASDF_DIR=/Users/nurrony/.zi/plugins/asdf-vm---asdf
ASDF_CONFIG_FILE=/Users/nurrony/.asdfrc

ASDF INSTALLED PLUGINS:
bun                          https://github.com/cometkim/asdf-bun.git main 51d18b3
```

**Comment by cometkim** [comment]
Umm, do you have set `$GITHUB_API_TOKEN` in your env? If so try:
```sh
curl \
    -H 'Accept: application/vnd.github+json' \
    -H "Authorization: token $GITHUB_API_TOKEN" \
    "https://api.github.com/repos/oven-sh/bun/releases"
```

**Comment by nurrony** [comment]
@cometkim, I don't have `GITHUB_API_TOKEN` in my env. Do I need to one? if yes, does it not sound little inconvenient?

**Comment by cometkim** [comment]
No, I thought there was no way to get any error then. 🤔

**Comment by nurrony** [comment]
@cometkim I just tried your `curl` command by setting `GITHUB_API_TOKEN` as System Environment Variable. It works fine. But when I  run `asdf list all bun` getting this following error. 
<img width="1440" alt="snapshot-20231008134909@2x" src="https://github.com/cometkim/asdf-bun/assets/2513341/b64844e8-e691-4223-87f8-d8550793dad9">

**Comment by cometkim** [comment]
Can you try `asdf plugin update bun` and again?

**Comment by nurrony** [comment]
@cometkim no luck back to the square 1 :( 
```sh
❯ asdf plugin update bun
Location of bun plugin: /Users/nurrony/.asdf/plugins/bun
Updating bun to main
From https://github.com/cometkim/asdf-bun
   51d18b3..a79462c  main       -> main
   51d18b3..a79462c  main       -> origin/main
Already on 'main'
Your branch is up to date with 'origin/main'.

❯ asdf list all bun
Plugin bun's list-all callback script failed with output:
<no output nothing>

```

**Comment by cometkim** [comment]
umm, I cannot reproduce the issue on same environment, maybe it is better to debug on your end

here is a standalone script equivalent to the `list-all`

```bash
#!/usr/bin/env bash

set -eo pipefail

GITHUB_REPO="oven-sh/bun"
REPO_URL="https://github.com/$GITHUB_REPO"

curl_opts=(-fsSL)
if [ -n "${GITHUB_API_TOKEN:-}" ]; then
  curl_opts=("${curl_opts[@]}" -H "Authorization: token $GITHUB_API_TOKEN")
fi

function sort_versions() {
  sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' |
    LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
}

function list_github_releases() {
  curl "${curl_opts[@]}" \
    -H "Accept: application/vnd.github+json" \
    "https://api.github.com/repos/$GITHUB_REPO/releases" |
    grep -o '"tag_name": "bun-v.*"' |
    sed -E 's/"tag_name": "bun-v(.*)"/\1/'
}

list_github_releases | sort_versions | sed 1,11d | xargs echo
```

Can you try this and report back what you find?

**Comment by nurrony** [comment]
@cometkim it does not return any result. same as `asdf list all bun`. Sorry for replying late.

**Comment by cometkim** [comment]
As you can see, it's not much.

To make it precise, you can test the commands one by one without piping. just `list_github_realeases` first.

Excluding `s`(slient) from `curl_opts` also help.
