### ISSUE TITLE
Global install doesn't place commands in PATH

### ISSUE THREAD

**Issue by doubledup** [cometkim/asdf-bun#18]
From [the docs](https://bun.sh/docs/cli/install#global-packages), `bun install --global cowsay` should make `cowsay` available. Instead I get `fish: Unknown command: cowsay`, even after `asdf reshim` and starting a new shell.

This is in `fish shell 3.6.1`, `kitty 0.30.1` and `macOS 14.1`. The same error occurs in the default `Terminal 2.14 (452)`, and in `bash 5.2.15(1)-release (aarch64-apple-darwin22.1.0)` and `zsh 5.9 (x86_64-apple-darwin23.0)`. Combinations of Terminal with bash & zsh also produce this error.

**Comment by cometkim** [comment]
Yep, I never implemented that feature. but has a plan to support it as described in https://github.com/cometkim/asdf-bun/issues/14#issuecomment-1726605808

**Comment by doubledup** [comment]
Thanks! 🙏 

Looks like the only thing missing for this is the shell rc file edits made by the bun install script. You mentioned this in the linked comment: "... users have to manually configure the `PATH`."

A workaround for anyone running into this is to run the bun install script to get the changes to your shell rc file:
```
asdf plugin remove bun
curl -fsSL https://bun.sh/install | bash
rm -rf ~/.bun/
asdf plugin add bun
```

The uninstall step comes [from the uninstall issue in bun](https://github.com/oven-sh/bun/issues/981#issuecomment-1205792391).

**Comment by cometkim** [comment]
@doubledup Just add `~/.bun/bin` to your `PATH` then you can use globally installed binaries

**Comment by cometkim** [comment]
And even you can customize your global installation path, see https://bun.sh/docs/runtime/bunfig#install-globalbindir

**Comment by cometkim** [comment]
However, I've changed my mind, I think it's not a role of this asdf plugin.

I think the current behavior of Bun is not suitable for managing global installations. See https://gist.github.com/cometkim/eb2842d67b40e583e4886e9b897a6af0

Maybe you can request the upstream to change its behavior to be more sensible

**Comment by cometkim** [comment]
just filed a ticket to upstream https://github.com/oven-sh/bun/issues/6928

**Comment by cometkim** [comment]
Bun has the problem of not being well suited to handle global installations (See https://github.com/oven-sh/bun/issues/6928)

I could override the behavior like the asdf-nodejs plugin does for npm, but I believe that's not the correct move. I would not recommend managing global installations via Bun until this is discussed upstream.
