### ISSUE TITLE
Add `canary` tagged releases to `list-all`

### ISSUE THREAD

**Issue by loicnestler** [cometkim/asdf-bun#22]
Bein able to install Bun's [canary](https://github.com/oven-sh/bun/releases/tag/canary) release would be great.

**Comment by cometkim** [comment]
I don't think it's really useful.

asdf was not built with tag-based use cases in mind, and users have to manually remove/install them when needed.

it might be useful when selecting wide ranges in tool-versions, but I can't imagine there being a `canary` there.

**Comment by cometkim** [comment]
I will add `latest-stable` that is [recommended by asdf](https://asdf-vm.com/plugins/create.html#bin-latest-stable), but I won't add any custom method then. Please open an issue to the upstream if you still want it
