### ISSUE TITLE
bunx doesn't work bun v1

### ISSUE THREAD

**Issue by ekweible** [cometkim/asdf-bun#24]
I've just tried installing the latest version of bun, which is v1.1.15, using this asdf-bun plugin. Unfortunately, running `bunx` after the fact gives me this error:

```
No preset version installed for command bunx
Please install a version by running one of the following:

asdf install bun 1.1.15

or add one of the following versions in your config file at /Users/<path-to-project>/.tool-versions
bun 0.6.8
bun 0.6.9
```

But the `.tool-versions` file in that project does specify a version of bun:
```
bun 1.1.15
```

Any ideas why that might be?

**Comment by cometkim** [comment]
do you have any existing alias on `bunx` in your shell config?

or try `which bunx`

**Comment by ekweible** [comment]
I tried a fresh install of this plugin on a different laptop and it worked fine, so this must be an alias or conflict issue with my other laptop. Sorry for the trouble!
