### ISSUE TITLE
Bun commands are terminated by ``signal SIGILL (Illegal instruction)``

### ISSUE THREAD

**Issue by datsfilipe** [cometkim/asdf-bun#5]
````bash
bun install --yarn
fish: Job 1, 'bun install --yarn' terminated by signal SIGILL (illegal instruction)
````

bun create, bun install, all the commands I'm trying result in this. I was only able to print the version with ``bun -v``

I'm using Arch
Linux kernel 5.19
Terminal kitty with fish shell (I tried bash too)
Bun plugin installed in 0.1.10

Obs: I installed bun without using the asdf plugin and it worked as expected.

**Comment by KlausEverWalkingDev** [comment]
As show in this [comment](https://github.com/oven-sh/bun/issues/67#issuecomment-1205545144), using the "-baseline" release stops this error from ocurr. I did the test and it worked :)

**Comment by datsfilipe** [comment]
But how do I select -baseline version in asdf? for me there is no option

**Comment by KlausEverWalkingDev** [comment]
You have to do it manually, at least until this repo creator add it as a option.
